Update UpBestIP.yml

diff --git a/.github/workflows/UpBestIP.yml b/.github/workflows/UpBestIP.yml
--- a/.github/workflows/UpBestIP.yml
+++ b/.github/workflows/UpBestIP.yml
@@ -13,16 +13,16 @@ jobs:
 
       - name: Filter Best IPs
         run: |
-          curl -s "${{ secrets.IP_SOURCE_URL }}" | grep -E "SG|JP|KR" | grep ":2096#" | sed 's/:2096#.*//' | head -30 > raw.txt
+          curl -s "${{ secrets.IP_SOURCE_URL }}" | grep -E "DE" | grep ":2087#" | sed 's/:2087#.*//' | head -30 > raw.txt
           touch filtered_ips.txt
           while IFS= read -r ip; do
-            res=$(timeout 10s curl -s "${{ secrets.PY }}/check?proxyip=$ip:2096" || echo "fail")
+            res=$(timeout 10s curl -s "${{ secrets.PY }}/check?proxyip=$ip:2087" || echo "fail")
             if [[ "$res" != "fail" ]] && echo "$res" | jq -e '.success == true' >/dev/null 2>&1; then
               ms=$(echo "$res" | jq -r '.responseTime' | grep -Eo '[0-9]+' || echo "9999")
               echo "$ip $ms" >> valid.txt
             fi
           done < raw.txt
-          [ -f valid.txt ] && sort -n -k2 valid.txt | head -10 | cut -d' ' -f1 > filtered_ips.txt
+          [ -f valid.txt ] && sort -n -k2 valid.txt | head -5 | cut -d' ' -f1 > filtered_ips.txt
           curl -s "${{ secrets.YXIP }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' > yx.txt
 
       # 设置 Python 环境
