Update UpBestIP.yml

diff --git a/.github/workflows/UpBestIP.yml b/.github/workflows/UpBestIP.yml
--- a/.github/workflows/UpBestIP.yml
+++ b/.github/workflows/UpBestIP.yml
@@ -13,16 +13,16 @@ jobs:
 
       - name: Filter Best IPs
         run: |
-          curl -s "https://zip.cm.edu.kg/all.txt" | grep "DE" | grep ":2096#" | sed 's/:2096#.*//' | head -60 > raw.txt
+          curl -s "https://zip.cm.edu.kg/all.txt" | grep "DE" | grep ":2096#" | sed 's/:2096#.*//' | head -50 > raw.txt
           touch filtered_ips.txt
           while IFS= read -r ip; do
-            res=$(timeout 5s curl -s "https://ip.kkki.qzz.io/check?proxyip=$ip" || echo "fail")
+            res=$(timeout 10s curl -s "https://ip.kkki.qzz.io/check?proxyip=$ip" || echo "fail")
             if [[ "$res" != "fail" ]] && echo "$res" | jq -e '.success == true' >/dev/null 2>&1; then
               ms=$(echo "$res" | jq -r '.responseTime' | grep -Eo '[0-9]+' || echo "9999")
               echo "$ip $ms" >> valid.txt
             fi
           done < raw.txt
-          [ -f valid.txt ] && sort -n -k2 valid.txt | head -10 | cut -d' ' -f1 > filtered_ips.txt
+          [ -f valid.txt ] && sort -n -k2 valid.txt | head -5 | cut -d' ' -f1 > filtered_ips.txt
 
       # 设置 Python 环境
       - name: 设置 Python 环境
